clusterId: cljdd692n
command: python xgboost_model.py
container: kandoenv/training:latest
experimentEnv:
#    POINT_IDS:
#        - "1012"
#        - "3226"
#        - "3256"
#        - "3436"
#        - "3668"
#        - "5058"
    START: 1554182371
    END: 1582008447
    PREDICTION_PARAM: EC
machineType: c5.xlarge
modelPath: /artifacts
modelType: Custom
name: josh_experiment_1
projectId: pr8s6cutt
registryPassword: null
registryUrl: null
registryUsername: null
tag: prophet
tensorboard: false
tensorboard_set: null
workspace: .
workspaceArchive: null
workspacePassword: null
workspaceRef: null
workspaceUrl: null
workspaceUsername: null
