clusterId: cljdd692n
command: python inference/training/trainer.py
container: kandoenv/training:latest
experimentEnv:
    START: 1554182371
    END: 1582008447
    PREDICTION_PARAM: EC
machineType: c5.xlarge
modelPath: /artifacts
modelType: Custom
name: CI_CD
